apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: azure-ml
  name: azure-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: azure-server
  template:
    metadata:
      namespace: azure-ml
      labels:
        name: azure-server
    spec:
      containers:
        - name: azure-server
          image: docker-image
          imagePullPolicy: Always
          command:
            - "bash"
            - "-c"
            - "streamlit run main.py"
          ports:
            - containerPort: 8080
              name: rest
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
      restartPolicy: Always
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
      imagePullSecrets:
        - name: azure-ml-secret

           
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

apiVersion: v1
kind: Service
metadata:
  namespace: azure-ml
  name: azure-server
spec:
  selector:
    name: azure-server
  ports:
    - port: 80
      targetPort: rest
  type: LoadBalancer